#include "Board/PowerEnvDaq/Inc/power_env_daq_board_resources.h"

static const board_resource_t power_env_daq_resources[] = {
  {
    "CH395Q Ethernet",
    BOARD_RESOURCE_NETWORK,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_READY,
    "UART4 + GPIO boot/status",
    "PC10 TX, PC11 RX, PA4 RSTI, PA5 RST status, PB0 SEL, PB12 SCS, PB1 RDY, PD13 INT",
    "WCH CH395 UART command/socket protocol",
    "Primary wired network path for MQTT and network probing; SPI-mode pins are reserved for boot strapping.",
  },
  {
    "Air724UG 4G modem",
    BOARD_RESOURCE_NETWORK,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_READY,
    "UART4 shared + GPIO reset/netstate",
    "UART4 shared with CH395Q, PE2 RST, PA1 NETSTATE",
    "AT command TCP/UDP socket protocol",
    "Fallback cellular path; CH395Q and Air724UG are isolated by reset before sharing UART4.",
  },
  {
    "AT24C EEPROM",
    BOARD_RESOURCE_STORAGE,
    BOARD_RESOURCE_SCOPE_COMMON,
    BOARD_RESOURCE_STATUS_READY,
    "I2C1",
    "PB6 SCL, PB7 SDA",
    "AT24C 7-bit address 0x50",
    "Stores runtime config and BASIC scripts through the existing EEPROM abstraction.",
  },
  {
    "RS485 field bus",
    BOARD_RESOURCE_EXPANSION,
    BOARD_RESOURCE_SCOPE_COMMON,
    BOARD_RESOURCE_STATUS_READY,
    "USART1 + GPIO direction",
    "PA9 TX, PA10 RX, PA12 RE/DE",
    "Modbus RTU",
    "Main data-acquisition bus for power/environment devices such as meters, switches, sensors, and UPS interfaces.",
  },
  {
    "Power/environment devices",
    BOARD_RESOURCE_SENSOR,
    BOARD_RESOURCE_SCOPE_COMMON,
    BOARD_RESOURCE_STATUS_READY,
    "RS485 field bus",
    "via USART1/PA9/PA10/PA12 transceiver",
    "Modbus RTU device protocols",
    "Shared device layer covers electricity meters, switches, temperature/humidity sensors, UPS interfaces, and similar acquisition targets.",
  },
  {
    "RS232 service port",
    BOARD_RESOURCE_EXPANSION,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_IOC_MAPPED,
    "UART5",
    "PC12 TX, PD2 RX",
    "serial 8N1",
    "Available to BASIC SERIAL_OPEN as RS232 port 5; concrete external device is deployment-specific.",
  },
  {
    "Debug console",
    BOARD_RESOURCE_DEBUG,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_READY,
    "USART2",
    "PA2 TX, PA3 RX",
    "115200 8N1",
    "Shell, logs, configuration commands, and firmware diagnostics.",
  },
  {
    "Buzzer",
    BOARD_RESOURCE_ACTUATOR,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_IOC_MAPPED,
    "GPIO",
    "PE7",
    "digital output",
    "Local audible indication; currently initialized as low-level GPIO output.",
  },
  {
    "RTC",
    BOARD_RESOURCE_USER_IO,
    BOARD_RESOURCE_SCOPE_COMMON,
    BOARD_RESOURCE_STATUS_IOC_MAPPED,
    "RTC + LSE",
    "PC14 LSE IN, PC15 LSE OUT",
    "calendar/timebase",
    "Local time retention and timestamps; network time sync remains a higher-level feature.",
  },
  {
    "Independent watchdog",
    BOARD_RESOURCE_USER_IO,
    BOARD_RESOURCE_SCOPE_COMMON,
    BOARD_RESOURCE_STATUS_READY,
    "IWDG",
    "internal LSI",
    "hardware watchdog",
    "Refresh is integrated into long network, MQTT, BASIC, and main-loop waits.",
  },
  {
    "CH395 SPI pin reservation",
    BOARD_RESOURCE_EXPANSION,
    BOARD_RESOURCE_SCOPE_BOARD_SPECIFIC,
    BOARD_RESOURCE_STATUS_IOC_MAPPED,
    "GPIO reservation",
    "PB12 SCS, PB13 SCK, PB14 MISO, PB15 MOSI",
    "reserved CH395 alternate interface",
    "Current firmware uses UART4 mode only; keep these pins documented because they affect CH395 boot/interface mode.",
  },
};

const board_resource_t *power_env_daq_board_resources(size_t *count) {
  if (count != NULL) {
    *count = sizeof(power_env_daq_resources) / sizeof(power_env_daq_resources[0]);
  }
  return power_env_daq_resources;
}
